# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2426b6a785633f7fbc662f3bb184187"
name = "Parallax"
application_url = "https://shopify-parallax.terosu.com"
embedded = true
handle = "parallax-yt"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify-parallax.terosu.com/api/auth" ]
